include_recipe '../../cookbooks/centos/yum/recipe.rb'
include_recipe '../../cookbooks/centos/nginx/nginx.rb'
include_recipe '../../cookbooks/common/vim/recipe.rb'
include_recipe '../../cookbooks/common/python/python3.rb'
include_recipe '../../cookbooks/common/go/recipe.rb'
include_recipe '../../cookbooks/common/redis/redis.rb'
